In [2]:
import pandas as pd
import numpy as np 


1. ¿Qué diferencia hay entre una Serie y un DataFrame?

- la serie es unidimensional, como un array de numpy
- DF es bidimensional

2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

- Crea dos listas:

- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [2]:
valores = [1, 2, 3, 4, 5, 6, 7]
indices = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]

A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [3]:
resultado_1 = pd.Series(valores, index=indices)
resultado_1

lunes        1
martes       2
miércoles    3
jueves       4
viernes      5
sábado       6
domingo      7
dtype: int64

A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [12]:
resultado = zip(valores, indices)

In [13]:
resultado_lista = list(resultado)
dict(resultado_lista)

{1: 'lunes',
 2: 'martes',
 3: 'miércoles',
 4: 'jueves',
 5: 'viernes',
 6: 'sábado',
 7: 'domingo'}

In [14]:
resultado_dict = dict(resultado_lista)

In [15]:
resultado_dict

{1: 'lunes',
 2: 'martes',
 3: 'miércoles',
 4: 'jueves',
 5: 'viernes',
 6: 'sábado',
 7: 'domingo'}

Crea una Serie con el diccionario creado en el punto anterior.

In [18]:
resultado_2 = pd.Series(resultado_dict)
resultado_2

1        lunes
2       martes
3    miércoles
4       jueves
5      viernes
6       sábado
7      domingo
dtype: object

- ¿Qué forma tiene esta última Serie?

In [22]:
resultado_2.shape
# te dice la cantidad de filas

(7,)

¿Qué tipo de datos tiene?


In [21]:
resultado_2.dtypes
# objeto 

dtype('O')

¿Qué tamaño tiene?


In [24]:
resultado_2.size
#cantidad de elementos que tiene la serie

7

¿Cuáles son los índices de la Serie?


In [25]:
resultado_2.index

Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')

¿Y los values?


In [26]:
resultado_2.values

array(['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado',
       'domingo'], dtype=object)

Extrae el valor para el índice "lunes"


In [32]:
var_lunes = resultado_2[1]
var_lunes

'lunes'

Extrae el valor para el índice "lunes", "martes" y "miércoles".


In [35]:
var_martes = resultado_2[0:3:1]
var_martes

1        lunes
2       martes
3    miércoles
dtype: object

Extrae el valor para el índice "lunes" y "domingo".

In [49]:
var_lun_dom = resultado_2[0:7:6]
var_lun_dom

#porque haciendo 0:-1:7 o 6, no sale domingo? 

1      lunes
7    domingo
dtype: object

3. Es el turno de los DataFrames
- Crea un array de dos dimensiones con 4 filas y 3 columnas.

In [53]:
array_2d = np.random.rand(2,4,3)
array_2d

array([[[0.65705971, 0.38074372, 0.55954046],
        [0.04878494, 0.15681769, 0.28040396],
        [0.71471374, 0.76781893, 0.57742199],
        [0.55894424, 0.70774905, 0.23151138]],

       [[0.79417432, 0.21443391, 0.31391869],
        [0.41334891, 0.98026863, 0.4085537 ],
        [0.58011819, 0.13203925, 0.09387166],
        [0.13869133, 0.09603988, 0.29956787]]])

- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [80]:
# hacemos un reshape de array_2d

reshaped_array = array_2d.reshape(8,3)
reshaped_array

array([[0.65705971, 0.38074372, 0.55954046],
       [0.04878494, 0.15681769, 0.28040396],
       [0.71471374, 0.76781893, 0.57742199],
       [0.55894424, 0.70774905, 0.23151138],
       [0.79417432, 0.21443391, 0.31391869],
       [0.41334891, 0.98026863, 0.4085537 ],
       [0.58011819, 0.13203925, 0.09387166],
       [0.13869133, 0.09603988, 0.29956787]])

In [77]:
indices = array_2d[0]
indices

array([[0.65705971, 0.38074372, 0.55954046],
       [0.04878494, 0.15681769, 0.28040396],
       [0.71471374, 0.76781893, 0.57742199],
       [0.55894424, 0.70774905, 0.23151138]])

In [81]:
df_pair = pd.DataFrame(reshaped_array, columns=["España", "Francia", "Italia"])
df_pair

España   Francia    Italia
0  0.657060  0.380744  0.559540
1  0.048785  0.156818  0.280404
2  0.714714  0.767819  0.577422
3  0.558944  0.707749  0.231511
4  0.794174  0.214434  0.313919
5  0.413349  0.980269  0.408554
6  0.580118  0.132039  0.093872
7  0.138691  0.096040  0.299568

In [60]:
array_2d

array([[[0.65705971, 0.38074372, 0.55954046],
        [0.04878494, 0.15681769, 0.28040396],
        [0.71471374, 0.76781893, 0.57742199],
        [0.55894424, 0.70774905, 0.23151138]],

       [[0.79417432, 0.21443391, 0.31391869],
        [0.41334891, 0.98026863, 0.4085537 ],
        [0.58011819, 0.13203925, 0.09387166],
        [0.13869133, 0.09603988, 0.29956787]]])

Descarga el archivo "medallas" y carga el DataFrame.

In [4]:
df_medallas = pd.read_csv("../da-promof-modulo3-sprint1-pairprogramming-Marga-Anabella/ficheros/medallas.csv", index_col=0)
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

Usando el loc extrae todas las columnas de la fila de Tailandia.

In [87]:
tailandia = df_medallas.loc[7, :]
tailandia

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

Usando el loc extrae todas las columnas de China e Irán.

In [89]:
china_iran = df_medallas.loc[[1,4], :]
china_iran

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [91]:
china_iran_medallas = df_medallas.loc[[1,4], ["Oro", "Plata", "Bronce"]]
china_iran_medallas

Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

Usando el iloc extrae la información de la India. Devolved todas las columnas.

In [92]:
india = df_medallas.iloc[5,:]
india

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [99]:
impares = df_medallas.iloc[1:11:2, :]
impares

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [102]:
impares = df_medallas.iloc[1:11:2, 1:4]
impares

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

Contesta a las siguientes preguntas:
- ¿Qué país consiguió más de 200 medallas de oro?
- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [105]:
oro = df_medallas.loc[df_medallas["Oro"]> 200, ["País", "Oro"]]
oro

País   Oro
1          China  1473
2          Japón  1032
3  Corea del Sur   745

In [110]:
plata = df_medallas.loc[(df_medallas["Plata"]>1000) & (df_medallas["Oro"]>200), ["País", "Oro", "Plata"]]
plata

País   Oro  Plata
2  Japón  1032   1037

In [113]:
bronce = df_medallas.loc[(df_medallas["Bronce"]>700) | (df_medallas["Oro"]>200), ["País", "Oro", "Bronce"]]
bronce

País   Oro  Bronce
1          China  1473     720
2          Japón  1032     985
3  Corea del Sur   745     827

Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [133]:
df_medallas["total"] = df_medallas[["Oro", "Plata", "Bronce"]].sum(axis=1)
#axis 1 son filas y axis 0 son columnas

In [132]:
df_medallas

País   Oro  Plata  Bronce  total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446

In [131]:
df_medallas.sum(axis=0) #como ejemplo de que 0 son columnas. 

País      ChinaJapónCorea del SurIránKazajistánIndiaTail...
Oro                                                    4172
Plata                                                  3805
Bronce                                                 4297
total                                                 12274
dtype: object