Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np
import random

In [3]:
array_1 = np.random.randint(10, 100, 50)

In [7]:
array_1[::5]

array([40, 67, 51, 24, 72, 49, 41, 44, 84, 74])

Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [10]:
array_2 = np.random.randint(1,21,30)

In [13]:
array_2[1::2]

array([ 1,  1, 12, 19,  3,  1,  9, 19,  1, 12, 16,  9,  5,  8,  2])

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [18]:
array_3 = np.random.rand(4,6)*20

In [21]:
#Accedemos ala ultima fila 
array_3[-1]
array_3[3]

array([19.08587588, 17.55266793,  3.79660984,  9.60044916,  6.93160455,
        3.75100454])

In [22]:
array_3 = (np.random.rand(4,6)*20).round(2)

Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [24]:
array_4 = np.random.rand(6,4)


In [31]:
array_4 

array([[0.42394069, 0.17227764, 0.7033087 , 0.73843006],
       [0.42966988, 0.02077811, 0.30277678, 0.70863026],
       [0.24845327, 0.83272128, 0.33197158, 0.42393269],
       [0.93112179, 0.01243616, 0.79964283, 0.92696582],
       [0.91638096, 0.54604672, 0.53927859, 0.25237176],
       [0.52842344, 0.38249078, 0.37161396, 0.71319457]])

In [30]:
array_4[:,1]

array([0.17227764, 0.02077811, 0.83272128, 0.01243616, 0.54604672,
       0.38249078])

In [32]:
array_4[3,1]

0.012436156849626179

In [33]:
array_4 = (np.random.rand(6,4)).round(2)

Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [35]:
array_5 = np.random.randint(-50, 51, 30)

In [36]:
array_5

array([-13, -26,  30,  -9, -25, -40,  19, -12,  19,   2,   3, -39, -48,
        35, -11,   8,  28,  -5, -47, -23,  40,   1,   4,  -7,  21,  47,
        -5,  21, -15,  29])

In [46]:
condicion= array_5 < 0


In [50]:
array_5[condicion]

array([-13, -26,  -9, -25, -40, -12, -39, -48, -11,  -5, -47, -23,  -7,
        -5, -15])


Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [51]:
array_6 = np.random.rand(10)

In [53]:
array_6 = (np.random.rand(10)).round(2)

In [54]:
array_6

array([0.22, 0.22, 0.9 , 0.73, 0.78, 0.96, 0.44, 0.63, 0.37, 0.97])

In [55]:
condicion_2 = array_6 > 0.5

In [58]:
np.where(condicion_2)

(array([2, 3, 4, 5, 7, 9]),)

Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [59]:
array_7 = np.random.randint(1,101, 40)

In [61]:
condicion_3= ((array_7 % 3 ==0) & (array_7 % 4 == 0))



Ejercicios con reshape:

Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [64]:
array_8= np.random.randint(1,101, (2,3,4))

In [65]:
array_8

array([[[22, 76, 13, 50],
        [25, 70, 60,  4],
        [84, 47, 52,  4]],

       [[38, 65, 23, 90],
        [27, 87, 30, 82],
        [ 2, 86,  9, 84]]])

In [72]:
array_modificada= np.reshape(array_8, (6,4))


Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [74]:
array_9 = np.random.randint(1,60, (3,4,5))

In [75]:
array_9

array([[[20, 59, 50, 43, 36],
        [30, 34,  2, 21, 36],
        [ 2, 11, 15, 46, 37],
        [51, 48, 43, 43, 27]],

       [[26, 29, 16, 38,  5],
        [33, 59, 47, 59, 20],
        [11, 40, 15, 59, 16],
        [33,  5, 16,  2, 48]],

       [[16,  9,  8, 21, 31],
        [15, 38, 36, 46, 37],
        [39, 39, 37,  4, 10],
        [43, 54, 25, 57, 34]]])

In [76]:
array_modificada_2 = np.reshape(array_9, (10,6))

In [77]:
array_modificada_2

array([[20, 59, 50, 43, 36, 30],
       [34,  2, 21, 36,  2, 11],
       [15, 46, 37, 51, 48, 43],
       [43, 27, 26, 29, 16, 38],
       [ 5, 33, 59, 47, 59, 20],
       [11, 40, 15, 59, 16, 33],
       [ 5, 16,  2, 48, 16,  9],
       [ 8, 21, 31, 15, 38, 36],
       [46, 37, 39, 39, 37,  4],
       [10, 43, 54, 25, 57, 34]])

In [82]:
array_modificada_2 = np.reshape(array_9, (4,15))

In [83]:
array_modificada_2

array([[20, 59, 50, 43, 36, 30, 34,  2, 21, 36,  2, 11, 15, 46, 37],
       [51, 48, 43, 43, 27, 26, 29, 16, 38,  5, 33, 59, 47, 59, 20],
       [11, 40, 15, 59, 16, 33,  5, 16,  2, 48, 16,  9,  8, 21, 31],
       [15, 38, 36, 46, 37, 39, 39, 37,  4, 10, 43, 54, 25, 57, 34]])

Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [85]:
array_10 = np.random.rand(4,3,2)

In [87]:
array_2d = np.reshape(array_10, (6,4))

In [88]:
array_2d

array([[0.17976693, 0.00870151, 0.20948356, 0.57847263],
       [0.28001423, 0.43774586, 0.59611927, 0.30476006],
       [0.12079216, 0.12284993, 0.87264118, 0.09400857],
       [0.45967163, 0.0960861 , 0.00588169, 0.45336033],
       [0.93557947, 0.50889393, 0.42230802, 0.21029677],
       [0.55399533, 0.53175118, 0.9433145 , 0.43714609]])